#!/bin/bash
set -e

# Load environment variables from .env if it exists
if [ -f .env ]; then
  echo "Loading environment variables from .env..."
  while IFS= read -r line || [ -n "$line" ]; do
    # Strip carriage returns (Windows/DOS line endings support)
    line=$(echo "$line" | tr -d '\r')
    # Skip comments and empty lines
    case "$line" in
      \#*|"") continue ;;
    esac
    
    # Split at the first '='
    key=$(echo "$line" | cut -d'=' -f1 | xargs)
    val=$(echo "$line" | cut -d'=' -f2- | xargs)
    
    # Strip surrounding quotes from value if present
    val=$(echo "$val" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
    
    # Only set if not already set in shell environment
    eval "current_val=\"\${$key}\""
    if [ -z "$current_val" ]; then
      export "$key=$val"
    fi
  done < .env
fi

echo "Generating lib/firebase_options.dart from environment variables..."

# This script runs in the web deploy pipeline, so the web Firebase config is
# mandatory. Fail fast on a missing key instead of emitting an options file
# with empty strings — that would compile fine but crash Firebase.initializeApp
# at runtime (blank white screen) with no obvious cause.
if [ -z "$FIREBASE_API_KEY_WEB" ]; then
  echo "Error: FIREBASE_API_KEY_WEB is not set." >&2
  echo "Set the FIREBASE_* environment variables in your Vercel project settings." >&2
  echo "Source them from Firebase Console -> Project Settings -> Your apps -> Web app." >&2
  exit 1
fi

cat <<EOF > lib/firebase_options.dart
// File generated by Vercel Build Script
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// \`\`\`dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// \`\`\`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '${FIREBASE_API_KEY_WEB}',
    appId: '${FIREBASE_APP_ID_WEB}',
    messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}',
    projectId: '${FIREBASE_PROJECT_ID}',
    authDomain: '${FIREBASE_AUTH_DOMAIN}',
    storageBucket: '${FIREBASE_STORAGE_BUCKET}',
    measurementId: '${FIREBASE_MEASUREMENT_ID}',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '${FIREBASE_API_KEY_ANDROID}',
    appId: '${FIREBASE_APP_ID_ANDROID}',
    messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}',
    projectId: '${FIREBASE_PROJECT_ID}',
    storageBucket: '${FIREBASE_STORAGE_BUCKET}',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '${FIREBASE_API_KEY_IOS}',
    appId: '${FIREBASE_APP_ID_IOS}',
    messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}',
    projectId: '${FIREBASE_PROJECT_ID}',
    storageBucket: '${FIREBASE_STORAGE_BUCKET}',
    iosClientId: '${FIREBASE_IOS_CLIENT_ID}',
    iosBundleId: '${FIREBASE_IOS_BUNDLE_ID}',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '${FIREBASE_API_KEY_IOS}',
    appId: '${FIREBASE_APP_ID_IOS}',
    messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}',
    projectId: '${FIREBASE_PROJECT_ID}',
    storageBucket: '${FIREBASE_STORAGE_BUCKET}',
    iosClientId: '${FIREBASE_IOS_CLIENT_ID}',
    iosBundleId: '${FIREBASE_IOS_BUNDLE_ID}',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '${FIREBASE_API_KEY_WEB}',
    appId: '${FIREBASE_APP_ID_WINDOWS}',
    messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}',
    projectId: '${FIREBASE_PROJECT_ID}',
    authDomain: '${FIREBASE_AUTH_DOMAIN}',
    storageBucket: '${FIREBASE_STORAGE_BUCKET}',
    measurementId: '${FIREBASE_MEASUREMENT_ID_WINDOWS}',
  );
}
EOF

echo "lib/firebase_options.dart generated successfully."

# Regenerate .env only if running in Vercel or .env does not exist.
# This prevents overwriting local .env configurations (e.g. Android signing keys) during development.
if [ "$VERCEL" = "1" ] || [ ! -f .env ]; then
  echo "Generating .env file..."
  KEYS="
    FIREBASE_API_KEY_WEB
    FIREBASE_APP_ID_WEB
    FIREBASE_MESSAGING_SENDER_ID
    FIREBASE_PROJECT_ID
    FIREBASE_AUTH_DOMAIN
    FIREBASE_STORAGE_BUCKET
    FIREBASE_MEASUREMENT_ID
    FIREBASE_API_KEY_ANDROID
    FIREBASE_APP_ID_ANDROID
    FIREBASE_API_KEY_IOS
    FIREBASE_APP_ID_IOS
    FIREBASE_IOS_CLIENT_ID
    FIREBASE_IOS_BUNDLE_ID
    FIREBASE_APP_ID_WINDOWS
    FIREBASE_MEASUREMENT_ID_WINDOWS
  "

  touch .env
  truncate -s 0 .env

  for key in $KEYS; do
    eval value="\\$$key"
    if [ -n "$value" ]; then
      echo "$key=$value" >> .env
    fi
  done
  echo ".env generated successfully."
else
  echo "Existing .env file detected and not in Vercel. Skipping .env regeneration to preserve local variables."
fi
